#!/bin/bash
clear
czas1=3
czas2=30
czas3=90
czas=$czas1
rozmiar1=1000
rozmiar2=250000
while [ $czas -ge 0 ]
do
    find ./ -ctime $czas -size -$rozmiar1
    czas=$((czas-1))
done
czas=$czas3
echo ""
while [ $czas -ge $czas2 ]
do
    find ./ -ctime $czas -size +$rozmiar2
    czas=$((czas-1))
done
