#!/bin/bash
clear
nazwa=$1
nazwa2=$2
nazwa3=$3
ls
echo""
echo " Tworzenie pliku"
touch $nazwa
echo ""
ls
echo""
echo "Tworzenie katalogu"
mkdir $nazwa2
echo ""
ls
echo""
echo "Zmiana nazwy pliku"
mv $nazwa $nazwa3
echo ""
ls
echo ""
echo "Zmiana uprawnien"
ls -l
echo ""
echo "Czy chcesz zmienic uprawnienia pliku? tak - 1 nie - 0"
echo ""
read warunek
prawda=1
if [ $warunek -eq $prawda ]
   then
       chmod 700 $nazwa3
fi
echo ""
ls -l
echo ""
ls
echo ""
echo "Usuwanie plikow"
rm $nazwa3
rmdir $nazwa2
echo ""
ls
