#!/bin/bash
clear
ls
echo""
echo " Tworzenie pliku o nazwie plik.txt"
touch plik.txt
echo ""
ls
echo""
echo "Tworzenie katalogu o nazwie katalog"
mkdir katalog
echo ""
ls
echo""
echo "Zmiana nazwy pliku"
mv plik.txt plik123.txt
echo ""
ls
echo ""
echo "Zmiana uprawnien."
ls -l
echo""
chmod 700 plik123.txt
echo ""
ls -l
echo ""
ls
echo""
echo "Usuwanie plikow"
rm plik123.txt
rmdir katalog
echo ""
ls
